---
- name: Install Apache
  hosts: all
  force_handlers: true
  vars_files:
    - "vars/apache_{{ ansible_os_family }}.yml"

  handlers:
    - import_tasks: handlers/apache.yml

  # pre_tasks:
  #   # - debug: var=ansible_os_family
  #   - name: Load variable files
  #     include_vars: "{{ item }}"
  #     with_first_found:
  #       - "vars/apache_{{ ansible_os_family }}.yml"

  tasks:  
    - import_tasks: tasks/apache.yml