---
- hosts: centos
  become: true

  handlers:
    - name: restart_ssh
      service:
        name: sshd
        state: restarted

  tasks:
    - name: Tell SELinux about SSH's new port
      seport:
        ports: 2849
        proto: tcp
        setype: ssh_port_t
        state: present

    - name: Make sure SSH is more secure
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
        # validate: 'ssh -T -f %s'
      with_items:
        - regexp: "^PasswordAuthentication"
          line: "PasswordAuthentication no"
        - regexp: "^PermitRootLogin"
          line: "PermitRootLogin no"
        - regexp: "^#Port"
          line: "Port 2849"
      notify: restart_ssh

    - name: Add user johndoe
      user:
        name: johndoe

    - name: Add sudo group rights for deployment user
      lineinfile:
        dest: /etc/sudoers
        regexp: "^johndoe"
        line: 'johndoe ALL=(ALL) NOPASSWD: ALL'
        state: present
        validate: 'visudo -cf %s'

    - name: Remove unused packages
      package:
        name:
          - httpd
          - nano
          - mailutils
        state: absent

    - name: Edit file permissions
      file:
        path: /etc/ssh/sshd_config
        mode: 0600

    # - name: Make sure everything is up to date on RehHat Family
    #   yum:
    #     name: '*'
    #     state: latest

    # - name: Make sure everything is up to date on Debian Family
    #   package:
    #     upgrade: dist
    #     update_cache: yes

    - name: Set up autoupdates
      yum:
        name: dnf-automatic
        state: present

    - name: Ensure auto updates are running
      service:
        name: dnf-automatic-install.timer
        state: started
        enabled: true
