# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/ubuntu2004"

  config.ssh.insert_key = false

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider :virtualbox do |v|
    v.memory = 1024
    v.linked_clone = true
  end

  # solr server 1
  config.vm.define "solr" do |app|
    app.vm.hostname = "orc-solr.test"
    app.vm.network :private_network, ip: "192.168.60.10"
  end
end
