---
- name: Install Apache
  hosts: all
  force_handlers: true
  vars_files:
    - "vars/apache_{{ ansible_os_family }}.yml"

  handlers:
    - name: reload apache
      service:
        name: "{{ apache_service }}"
        state: restarted

  # pre_tasks:
  #   # - debug: var=ansible_os_family
  #   - name: Load variable files
  #     include_vars: "{{ item }}"
  #     with_first_found:
  #       - "vars/apache_{{ ansible_os_family }}.yml"

  tasks:  
    - name: Ensure Apache is installed
      package:
        name: "{{ apache_package }}"
        state: present
        update_cache: true

    - name: Copy test config file
      copy:
        src: files/test.conf
        dest: "{{ apache_config_dir }}/test.conf"
      notify:
        - reload apache

    - name: Make sure handlers are flushed immediately
      meta: flush_handlers

    - name: Ensure Apache is running and starts at boot
      service:
        name: "{{ apache_service }}"
        state: started
        enabled: true
