---
- hosts: all
  gather_facts: false

  vars:
    my_color: '#00f'

  tasks:
    - name: "Verify {{ my_color }} is a form of blue"
      assert:
        that: >
          my_color == 'blue'
          or my_color == '#0000ff'
          or my_color == '#00f'
