---
- name: Install Apache
  hosts: all
  become: true

  tasks:
    - name: Install Apache
      yum:
        name:
          - httpd
          - httpd-devel
        state: present

    - name: Copy configuration file
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0644
      loop:
        - {src: 'httpd.conf', dest: '/etc/httpd/conf/httpd.conf'}
        - {src: 'httpd-vhosts', dest: '/etc/httpd/conf/httpd-vhosts.conf'}

    - name: Make sure Apache is started now and at boot
      service:
        name: httpd
        state: started
        enabled: true
